apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-meetup-hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pawelmuszynski/argocd-meetup-manifests.git
    targetRevision: master
    path: hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: meetup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
